# Generated by Django 4.2.5 on 2023-09-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_seconds', models.IntegerField()),
                ('task_id', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=30, null=30)),
            ],
        ),
    ]
